# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Inhibitory'), ('EX', 'Excitory')], default='EX', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type', models.TextField(default='Any')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=24)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflow.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workflow.Case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('section', models.CharField(default='default', max_length=128)),
                ('transition_class', models.CharField(max_length=128)),
                ('view', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('inputs', models.ManyToManyField(blank=True, related_name='targets', through='workflow.Arc', to='workflow.Location')),
                ('net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.Net')),
                ('outputs', models.ManyToManyField(blank=True, related_name='sources', to='workflow.Location')),
            ],
        ),
        migrations.AddField(
            model_name='net',
            name='starting_tokens',
            field=models.ManyToManyField(blank=True, to='workflow.Token'),
        ),
        migrations.AddField(
            model_name='message',
            name='origin',
            field=models.ManyToManyField(default=None, related_name='messages', to='workflow.Transition'),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='workflow.Transition'),
        ),
        migrations.AddField(
            model_name='location',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='workflow.Net'),
        ),
        migrations.AddField(
            model_name='case',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='workflow.Net'),
        ),
        migrations.AddField(
            model_name='arc',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='workflow.Location'),
        ),
        migrations.AddField(
            model_name='arc',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='workflow.Transition'),
        ),
    ]
