# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='token',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workflow.Location'),
        ),
    ]
