# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel("Argument", "Parameter")
    ]
