# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 16:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170405_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='color',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
