# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170120_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
