# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170220_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='parameters',
            new_name='arguments',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Operation'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Value'),
        ),
    ]
