# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170220_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='arguments',
            new_name='args',
        ),
    ]
