# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170406_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workflow.Case'),
        ),
    ]
