# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170406_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='workflow.Net'),
        ),
    ]
