# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170412_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='view',
            field=models.TextField(blank=True, null=True),
        ),
    ]
