# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_location_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='section',
        ),
        migrations.AddField(
            model_name='message',
            name='section',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
