# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170412_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='starting_tokens',
            field=models.ManyToManyField(blank=True, related_name='net', to='workflow.Token'),
        ),
    ]
