# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20170413_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='request_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='workflow.Message'),
        ),
    ]
