# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_token_request_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='request_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_token', to='workflow.Message'),
        ),
    ]
