# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170413_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='starting_tokens',
        ),
        migrations.AddField(
            model_name='token',
            name='net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workflow.Net'),
        ),
        migrations.AddField(
            model_name='token',
            name='starts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_tokens', to='workflow.Net'),
        ),
    ]
