# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20170421_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='unique_at_location',
            field=models.BooleanField(default=False),
        ),
    ]
