# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_token_unique_at_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_token_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
