# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_message_response_token_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='request_message',
        ),
        migrations.AddField(
            model_name='token',
            name='request_messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='response_tokens', to='workflow.Message'),
        ),
    ]
