# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('base_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
    ]
